train:
  max_epochs: 5
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  gradient_clip_val: 1
  accumulate_grad_batches: 1
  enable_progress_bar: true
  deterministic: false
  num_sanity_val_steps: 2
